name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Setup PHP
      uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
      with:
        php-version: '7.3'
        coverage: none
        tools: 'composer:v1'

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Lint
      run: composer lint

  Validate:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Setup PHP
      uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
      with:
        php-version: '7.3'
        coverage: none
        tools: 'composer:v1'

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Validate
      run: composer psalm

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Setup PHP
      uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
      with:
        php-version: '7.3'
        coverage: xdebug
        tools: 'composer:v1'

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Set up Mock Server
      run: |
        node -v
        cd tests/MockAPNSServer 
        yarn setup
        yarn install
        yarn serve &
        cd -

    - name: Test
      run: composer test
